run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    gocritic:
      enabled-checks:
        - appendAssign
        - argOrder
        - assignOp
        - badCond
        - boolExprSimplify
        - builtinShadow
        - captLocal
        - caseOrder
        - codegenComment
        - commentedOutCode
        - commentedOutImport
        - defaultCaseOrder
        - deprecatedComment
        - docStub
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - elseif
        - emptyFallthrough
        - equalFold
        - flagDeref
        - flagName
        - hexLiteral
        - ifElseChain
        - importShadow
        - indexAlloc
        - initClause
        - methodExprCall
        - nilValReturn
        - octalLit
        - offBy1
        - paramTypeCombine
        - ptrToRefParam
        - rangeExprCopy
        - rangeValCopy
        - regexpMust
        - singleCaseSwitch
        - sloppyLen
        - stringXbytes
        - switchTrue
        - typeAssertChain
        - typeSwitchVar
        - typeUnparen
        - underef
        - unlabelStmt
        - unlambda
        - unslice
        - valValReturn
        - wrapperFunc
        - yodaStyleExpr

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - gochecknoglobals
          - gosec
          - noctx
          - revive
      - path: examples/
        linters:
          - gosec
          - noctx

  disable-all: true
  enable:
    - copyloopvar
    - dogsled
    - err113
    - errorlint
    - exhaustive
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - revive
    - unconvert
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0