version: "2"

run:
  timeout: 10m
  go: "1.24"
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused

issues:
  max-issues-per-linter: 10
  max-same-issues: 3
  exclude-rules:
    # Exclude examples and tests from style checks - they are demonstration code
    - path: examples/
      linters:
        - revive
        - gosec
        - staticcheck
        - gci
    - path: tests/
      linters:
        - revive
        - gosec
        - staticcheck
        - gci
    - path: _test\.go
      linters:
        - all

output:
  format: colored-line-number
  print-linter-name: true
  sort-results: true